{
 "title": "health-analytics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT\r\n     date_trunc('minute', timestamp) AS time,\r\n     ROUND(AVG(heart_rate), 1) AS avg_heart_rate\r\n   FROM heartbeats\r\n   WHERE $__timeFilter(timestamp)\r\n   GROUP BY 1\r\n   ORDER BY 1"
    }
   ]
  },
  {
   "title": "Live Heart Rate per Patient",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT timestamp AS time, heart_rate, CAST(patient_id AS TEXT) AS metric\r\n   FROM heartbeats\r\n   WHERE $__timeFilter(timestamp)\r\n   ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Current Patient Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT DISTINCT ON (patient_id)\r\n     patient_id,\r\n     heart_rate,\r\n     status,\r\n     timestamp\r\n   FROM heartbeats\r\n   ORDER BY patient_id, timestamp DESC"
    }
   ]
  },
  {
   "title": "Anomaly Count per Minute",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT\r\n     date_trunc('minute', timestamp) AS time,\r\n     COUNT(*) AS anomalies\r\n   FROM heartbeats\r\n   WHERE status != 'normal'\r\n     AND $__timeFilter(timestamp)\r\n   GROUP BY 1\r\n   ORDER BY 1"
    }
   ]
  },
  {
   "title": "Status Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "   SELECT status, COUNT(*) AS count\r\n   FROM heartbeats\r\n   WHERE $__timeFilter(timestamp)\r\n   GROUP BY status"
    }
   ]
  },
  {
   "title": "Anomaly Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT\r\n     ROUND(\r\n       100.0 * COUNT(*) FILTER (WHERE status != 'normal') / COUNT(*), 2\r\n     ) AS anomaly_rate_pct\r\n   FROM heartbeats\r\n   WHERE $__timeFilter(timestamp)"
    }
   ]
  }
 ]
}